// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3mCszoq9HLxIlC406JdWsD_uJu0V4FTA',
    appId: '1:204542154592:android:fb6f9e18cc5a12c945f005',
    messagingSenderId: '204542154592',
    projectId: 'todo-app-e4f44',
    storageBucket: 'todo-app-e4f44.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXg17n-IkCrgeQ2k0r1BqOnjLkHcGsgfg',
    appId: '1:204542154592:ios:d0df1369687f354645f005',
    messagingSenderId: '204542154592',
    projectId: 'todo-app-e4f44',
    storageBucket: 'todo-app-e4f44.appspot.com',
    androidClientId: '204542154592-hob2vnb3di9ukg1a7jqeked150sff08i.apps.googleusercontent.com',
    iosClientId: '204542154592-8j96rl05kd0m8u2kld0cvqmojenovki2.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalTodo2',
  );
}
